server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001

database:
  driverClass:  org.postgresql.Driver
  username: balaji
  password: password
  url:  personal.cl8mah0cypgj.us-east-2.rds.amazonaws.com
  name: personal
  port: 5432

flywayMigration: false
